#\u914D\u7F6E\u4FE1\u606F
myConfig:
  myObject:
    myName: zhangsan
    myAge: 18
config:
  #mysql\u914D\u7F6E\u4FE1\u606F
  mysql:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
#  #redis\u914D\u7F6E\u4FE1\u606F
#  redis:
#    ip: 127.0.0.1
#    port: 6379
#    auth: 123456